[package]
name = "rag-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.8.9", features = ["multipart"] }
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.7.1", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"

serde = { version = "1", features = ["derive"] }
serde_json = "1"

sqlx = { version = "0.9", features = ["postgres", "runtime-tokio", "tls-rustls-ring-webpki", "macros"] }
pgvector = { version = "0.4", features = ["sqlx"] }

dotenvy = "0.15"
anyhow = "1"


